[build]
builder = "nixpacks"
watchPatterns = ["server/**"]

[deploy]
startCommand = "cd server && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3